### ISSUE TITLE
Use with existing mail

### ISSUE THREAD

**Issue by pelle999** [jonufele/WaterCooler-Chat#2]
If i run the chat from my Synology NAS-server without a mailserver installed, it not possible to get the password back, how can I use an existing mail, ex, gmail or outlook? (Me in private think that it would be easier to handle it that way.)

**Comment by jonufele** [comment]
You cant send a recover email from a server if that server cant send emails, period.

**Comment by rexzooly** [comment]
> If i run the chat from my Synology NAS-server without a mailserver installed, it not possible to get the password back, how can I use an existing mail, ex, gmail or outlook? (Me in private think that it would be easier to handle it that way.)

This could be done where the user would email you from the account that is registered with you and you then reset the password for them, you could also use maybe a free host that lets them do the email forgot part and then that website sends a API request to yoursite then sets up the forgotten password part.

There are a few ways around it.

**Comment by jonufele** [comment]
This can be done by changing the default mail call by a SMTP call.
Either way, the lack of donations mean this integration will be left out.
