### ISSUE TITLE
Deprecated @ PHP 8.2

### ISSUE THREAD

**Issue by oliveskur** [jonufele/WaterCooler-Chat#5]
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in C:\http\ww\chat\includes\classes\wcutils.class.php on line 219

Deprecated: Implicit conversion from float 1687728017.8812 to int loses precision in C:\http\ww\chat\includes\classes\wcroom.class.php on line 1187

Deprecated: Implicit conversion from float 1687728017.8812 to int loses precision in C:\http\ww\chat\includes\classes\wcroom.class.php on line 1214

**Comment by rexzooly** [comment]
I have put in a pull request 

https://github.com/jonufele/WaterCooler-Chat/pull/6

**Comment by jonufele** [comment]
Fixes already present on latest release
