### ISSUE TITLE
Why not make it mobile resposive?

### ISSUE THREAD

**Issue by tasinone** [jonufele/WaterCooler-Chat#7]
Hey, can you make it mobile-responsive?

**Comment by jonufele** [comment]
Why not make a donation? :)

**Comment by jonufele** [comment]
This will be available on v1.5.2

**Comment by tasinone** [comment]
Thanks, bro. Also, I am from a country where there is no PayPal, no Gpay, or nothing. That's why only a few of us can make a donation. Because very few of us hold a credit card.
